### ISSUE TITLE
Restore does not restore files.

### ISSUE THREAD

**Issue by ghost** [jdaehne/BackupMODX#61] opened 2021-02-23 06:13 UTC
There is no option given to restore files, and files are not restored. 

<img width="542" alt="Screen Shot 2021-02-23 at 7 21 59" src="https://user-images.githubusercontent.com/1073780/108808266-ea43c000-75ae-11eb-839c-da7b41f96232.png">

**Comment by Jako** [comment] 2021-04-22 06:45
Duplicate of #58

**Closed as completed by Jako** 2021-04-22 06:45 UTC
